openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
paths:
  /greeting:
    get:
      summary: Returns a greeting
      operationId: getGreeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
