---
name: Validate Java with Maven

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.release.tag_name || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '21', '20', '17']
    name: Java ${{ matrix.Java }} CI with Maven
    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: maven
      - name: Build with Maven
        run: mvn -B verify
      - name: Install new project archetype
        run: mvn -B clean install
      - name: Create a directory outside the repo
        run: |
          mkdir -p ../new-project
      - name: Generate New Project Archetype
        working-directory: ../new-project
        run:  |
          mvn archetype:generate \
            -DarchetypeGroupId=com.xgeeks.template \
            -DarchetypeArtifactId=maven-archetype-api \
            -DarchetypeVersion=1.0-SNAPSHOT \
            -DgroupId=com.example.myapp \
            -DartifactId=generated-api-from-template \
            -Dversion=1.0-SNAPSHOT \
            -DinteractiveMode=true -X
      - name: Validate generated project
        run: |
          cd generated-api-from-template
          mvn -B verify
